#!/bin/bash

python main.py < problem352-attempt1.in
